formularios_tareas:
    resource: "@FormulariosTareasBundle/Controller/"
    type:     annotation
    prefix:   /form

route_db:
    resource: "@dbBundle/Controller/"
    type: annotation
    prefix:   /db

app:
    resource: '@AppBundle/Controller/'
    prefix:   /
    type: annotation
